msg_title = "Shapefile to SSAP files"
versione = "1.1.8 - build 209"
root_title = "Conversione Shapefile in file per SSAP - Shp2SSAP [ Ver. " + versione + "]"
msg_title = "Shapefile to SSAP files"
msg_title_error = msg_title + " - Gestione errori"
msg_title_check = msg_title + " - Verifica Tipo e Campi Shapefile"
msg_err_end1 = "\n ##### Controllare lo shapefile di input e ripetere la procedura \t"
msg_err_end2 = "\n ##### Indicare il nome dei file SSAP di output e ripetere la procedura \t"
header_msg_error = "Si e' verificato un errore non previsto!\n La procedura termina \n\n Descrizione dell'errore: \n"
msg_error01 = ("ERRORE 01 - Si e' verificato un errore nel caricamento dello shapefile\n"
"La procedura termina\n\n Descrizione dell'errore: \n ")
msg_error02 = "\nERRORE 02: mancano i seguenti campi per i file per SSAP (configurazione base file .dat, .geo e .mod):"
msg_error03 = "\nERRORE 03: Nel campo SSAP risultano presenti i seguenti valori errati o incoerenti rispetto alle specifiche SSAP: "
msg_error04 = "\nERRORE 04: Lo shapefile non e' del tipo 'polyline'\n"
msg_error11 = ("\nERRORE 11: Possibili problemi con l'ordinamento verticale dei valori ssap_id per i layer 'dat'.\n"
"Attenzione: per modelli complessi sono possibili false segnalazioni di errore. "
"In tal caso riprovare escludendo la 'verifica ordinamento verticale strati'\n")
msg_error_import = "Errore nell'importazione dei moduli di python.\n"
"Possibile errore di installazione o utilizzo errato del file sorgente"
xy2Shp_forSSAP_str = "xy2Shp_forSSAP_095_023_beta.py"
